### ISSUE TITLE
删除父分类该父分类下的接口不会删除

### ISSUE THREAD

**Issue by MumfordSons** [zybieku/yapi#1]
1.初始结构如下
![image](https://user-images.githubusercontent.com/45234194/143996423-bce86506-819a-4aae-adb9-62e3fc65add7.png)
2.将分类1移入到分类2下
![image](https://user-images.githubusercontent.com/45234194/143996468-15ee71a5-dac7-4212-86f4-17d47dfc235f.png)
3.此时删除整个分类2，分类1的接口还会存留
![image](https://user-images.githubusercontent.com/45234194/143996590-abe4fce7-f147-47c4-904b-cc8efa6c01bd.png)

期望删除一个分类时，所有该目录下的子分类的接口全部删除

**Comment by zybieku** [comment]
> 1.初始结构如下 ![image](https://user-images.githubusercontent.com/45234194/143996423-bce86506-819a-4aae-adb9-62e3fc65add7.png) 2.将分类1移入到分类2下 ![image](https://user-images.githubusercontent.com/45234194/143996468-15ee71a5-dac7-4212-86f4-17d47dfc235f.png) 3.此时删除整个分类2，分类1的接口还会存留 ![image](https://user-images.githubusercontent.com/45234194/143996590-abe4fce7-f147-47c4-904b-cc8efa6c01bd.png)
> 
> 期望删除一个分类时，所有该目录下的子分类的接口全部删除

好，收到

**Comment by zybieku** [comment]
收到

**Comment by zybieku** [comment]
已解决
