### ISSUE TITLE
接口编辑页面”选择分类“能否替换成级联选择器

### ISSUE THREAD

**Issue by pangxieju** [zybieku/yapi#12]
<img width="1566" alt="QQ20220823-082637@2x" src="https://user-images.githubusercontent.com/18155203/186042439-c8ef8251-c9ae-49da-8742-3e1282d60914.png">
<img width="444" alt="180677475-77e4fb92-bb42-4cf2-ae09-ed2a3eae724f" src="https://user-images.githubusercontent.com/18155203/186042524-6203dffe-fdd6-43b9-849f-3d35d727ec87.png">

**Comment by zybieku** [comment]
已经解决,请更新版本
