### ISSUE TITLE
估计你代码合并出错，把自己的代码干没了

### ISSUE THREAD

**Issue by xuzhenjun130** [zybieku/yapi#19]
看github全局搜索,  upPidOrCid 这个方法你这里已经没有了，别人fork的分支还有

![image](https://github.com/zybieku/yapi/assets/4453516/761df3ff-26f7-4401-9133-600097b95819)

**Comment by xuzhenjun130** [comment]
@zybieku

**Comment by zybieku** [comment]
有可能,master分支 有时候用来fork用的, 没怎么看
你看feat分支,里面应该是有的
![IMG20240221163728](https://github.com/zybieku/yapi/assets/15903330/35179d3d-6260-4d36-89e1-4572719aff11)
