### ISSUE TITLE
目录删除后，在添加接口的接口分类中仍能看到

### ISSUE THREAD

**Issue by yanghe1117** [zybieku/yapi#2]
建的多级目录，删除其中一个目录，在右侧添加接口按钮弹出框里的接口分类中仍能看到已经删除的目录

![image](https://user-images.githubusercontent.com/12536366/144065656-809b0391-4d22-429e-9dd1-091932e5da42.png)

如上图，dddd已经删除，在左侧已经看不到了，但在添加接口的接口分类中仍有，不过f5刷新之后就没有了

**Comment by zybieku** [comment]
好的，我试下

**Comment by zybieku** [comment]
已经解决
