### ISSUE TITLE
接口分类的显示能否优化下？

### ISSUE THREAD

**Issue by yanghe1117** [zybieku/yapi#4]
![image](https://user-images.githubusercontent.com/12536366/146664003-98c9b096-e912-49d8-a6a0-801fe23bf133.png)

![image](https://user-images.githubusercontent.com/12536366/146664028-dcdbf1b2-f2b0-4262-adc8-b5bc005fd5b5.png)

新增接口时的接口分类以及编辑中的接口分类能否用/公共分类，/test1，/test1/p测试，/test1/p测试/test 这样来展示，因为如果现在这样显示的话有可能会名称相同但实际在不同的路径下

**Comment by zybieku** [comment]
可以

**Comment by zybieku** [comment]
已经解决,请更新版本
