### ISSUE TITLE
tags 里面的 v1.10.2-beta 版本保存 api 左侧菜单层级丢失

### ISSUE THREAD

**Issue by pangxieju** [zybieku/yapi#7]
对比了 maser 分支，发现v1.10.2-beta 下的 static\prd 目录里的文件没有更新；
<img width="872" alt="WX20220725-093316@2x" src="https://user-images.githubusercontent.com/18155203/180676612-710780e9-bd6c-440d-bd72-c0c6dbb2e863.png">

**Comment by zybieku** [comment]
请问这是哪里下载的,我重新上传一下

**Comment by pangxieju** [comment]
> 请问这是哪里下载的,我重新上传一下

在这里下载 https://github.com/zybieku/yapi/tags

**Comment by zybieku** [comment]
tag那里我传不了, 这是以前的版本的, 你可以用网盘或者其他地方的嘛

**Comment by pangxieju** [comment]
> tag那里我传不了, 这是以前的版本的, 你可以用网盘或者其他地方的嘛

问题也不大，我现在直接用的 `master` 分之。😂
