### ISSUE TITLE
点击父级目录展示子集所有 API

### ISSUE THREAD

**Issue by pangxieju** [zybieku/yapi#8]
完善了 yapi 不支持树目录的功能，非常棒！
能否支持下，点击父级目录显示所有子级目录的 API 的功能；
这样就不用一层层的往下点击了。
<img width="1164" alt="WX20220725-093711@2x" src="https://user-images.githubusercontent.com/18155203/180677152-3ada0a60-54d7-4c00-8709-d2be6424b784.png">

右侧 API 列表接口分类，能否替换成级联选择器。
<img width="1320" alt="WX20220725-094247@2x" src="https://user-images.githubusercontent.com/18155203/180677469-ee99ccba-327b-406d-9c19-fe6f86a0a0eb.png">

<img width="444" alt="WX20220725-094401@2x" src="https://user-images.githubusercontent.com/18155203/180677475-77e4fb92-bb42-4cf2-ae09-ed2a3eae724f.png">

**Comment by zybieku** [comment]
可以考虑下,但是这种场景多吗, 会有很多层的情况嘛, 我一般实际业务都是3-4级 不会再多了, 很多时候 我都不想全部展开!
`如果过有其他人也需要 ,确实可以加上这个 `

**Comment by pangxieju** [comment]
> 可以考虑下,但是这种场景多吗, 会有很多层的情况嘛, 我一般实际业务都是3-4级 不会再多了, 很多时候 我都不想全部展开! `如果过有其他人也需要 ,确实可以加上这个 `

这个 issues 一共有两个功能点；
第一个是左侧分类点击父分类显示所有子分类API，实际场景就是加了分类后现在需要点到子目录文件夹才能显示API。管理查找不是很方便。

第二个是右侧列表分类接口列显示问题，现在显示的是上级目录，只有一层。和第一个问题一样也是在查看管理的时候不方便。要是直接在列表上显示目录层次，就能很清除管理API。

感谢，感谢！

**Comment by zybieku** [comment]
添加接口 ,支持练级选择器
右侧列表分类接口 无法支持,因为 联级选择器无法确定你要选择那一层(可能你想选第一层就关闭弹框,或者第二层,第三.....,无法实现)
