### ISSUE TITLE
左侧目录删除接口，左侧列表条数缺失

### ISSUE THREAD

**Issue by pangxieju** [zybieku/yapi#9]
![WX20220730-111423](https://user-images.githubusercontent.com/18155203/181870489-77610756-45ad-4b1e-89c0-a02cdb043bba.png)

重现步骤：删除左侧目录接口；（上图红色区域）

绿色区域显示 15条，蓝色区域只有 10条信息。刷新页面数据正常。

**Comment by zybieku** [comment]
我看下 
实际问题 是蓝色区域显示问题 还是绿色区域

**Comment by pangxieju** [comment]
> 我看下 实际问题 是蓝色区域显示问题 还是绿色区域

是蓝色区域显示问题，蓝色区域 API 条数少了。

**Comment by zybieku** [comment]
已解决,请更新版本
